services:
    caddy:
    # This compose file uses caddy-docker-proxy as the reverse proxy for tuwunel!
    # For more info, visit https://github.com/lucaslorentz/caddy-docker-proxy
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        ports:
            - 80:80
            - 443:443
        environment:
            - CADDY_INGRESS_NETWORKS=caddy
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./caddy_data:/data
        restart: unless-stopped
        labels:
            caddy: luddlog.com
            caddy.0_respond: /.well-known/matrix/server {"m.server":"chat.luddlog.com:443"}
            caddy.1_respond: /.well-known/matrix/client {"m.server":{"base_url":"https://chat.luddlog.com"},"m.homeserver":{"base_url":"https://chat.luddlog.com"},"org.matrix.msc3575.proxy":{"url":"https://chat.luddlog.com"}}

    homeserver:
        image: jevolk/tuwunel:latest
        restart: unless-stopped
        volumes:
            - ./tuwunel_data:/var/lib/tuwunel
            - ./tuwunel.toml:/etc/tuwunel.toml
        environment:
            TUWUNEL_SERVER_NAME: luddlog.com # EDIT THIS
            TUWUNEL_DATABASE_PATH: /var/lib/tuwunel
            TUWUNEL_PORT: 6167
            TUWUNEL_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
            TUWUNEL_ALLOW_REGISTRATION: 'true'
            TUWUNEL_REGISTRATION_TOKEN: 'antif4' # A registration token is required when registration is allowed.
            #TUWUNEL_YES_I_AM_VERY_VERY_SURE_I_WANT_AN_OPEN_REGISTRATION_SERVER_PRONE_TO_ABUSE: 'true'
            TUWUNEL_ALLOW_FEDERATION: 'false'
            TUWUNEL_ALLOW_CHECK_FOR_UPDATES: 'true'
            TUWUNEL_TRUSTED_SERVERS: '["matrix.org"]'
            #TUWUNEL_LOG: warn,state_res=warn
            TUWUNEL_ADDRESS: 0.0.0.0
            TUWUNEL_CONFIG: '/etc/tuwunel.toml' # Uncomment if you mapped config toml above
        networks:
            - caddy
        labels:
            caddy: chat.luddlog.com
            caddy.reverse_proxy: "{{upstreams 6167}}"
    draupnir:
        image: gnuxie/draupnir:latest
        command: ["bot", "--draupnir-config", "/data/config/production.yaml"]
        restart: unless-stopped
        volumes:
            - ./draupnir_data:/data
            - ./draupnir.yml:/data/config/production.yaml
        networks:
            - draupnir

volumes:
    db:

networks:
    caddy:
        external: true
    draupnir:
        external: true
